### ISSUE TITLE
[BUG] GitHubLink ändern

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#11]
**Describe the bug**
Auf der Webseite ist noch der veraltete Link zu unserem Git. Bitte ersetzen mit: https://github.com/Nordland-Systems/nlp-website

**Comment by StevenPaw** [comment]
Fixed in 26e3b77dff78ee27ad2304a1cc86fa9e3a39cada

**Comment by zwibblTV** [comment]
Der Footer hat weiterhin den falschen Link

**Comment by StevenPaw** [comment]
Fixed in da831b5f211dbe18714ae6c0ffe63d5ee57434a9
