### ISSUE TITLE
[BUG] Kontaktformular-Fehler stylen

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#12]
**Describe the bug**
Fehlernachrichten beim Kontaktformular brauchen Abstände und (rote) Farben, damit sie nicht so aussehen:
![image](https://user-images.githubusercontent.com/29929054/178355191-f1d97ced-6ee0-48da-a972-60a0681189aa.png)

**Comment by StevenPaw** [comment]
Fixed in 584d2c133684b1533cb912f67d976f51058e9dc7
