### ISSUE TITLE
[BUG] Kontaktformular: Datum ist ungültig

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#13]
**Describe the bug**
Das Datum, wie bspw. der 20.11.2000, ist aktuell laut der Webseite kein gültiges Datum:
![image](https://user-images.githubusercontent.com/29929054/178355671-cecdb1b3-8852-4eb4-9655-63587d1dfc0f.png)

**Comment by StevenPaw** [comment]
Common error of the extension: https://github.com/silverstripe/silverstripe-userforms/issues/829
Will look further into the problem

**Comment by StevenPaw** [comment]
Fixed with 377bfbd3735f530bbda49731ebf6b223201df82c
