### ISSUE TITLE
[REQUEST] Countdown to Stream-Site

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#15]
Eine gestylte Site, die im Stream eingebunden werden kann:

- Countdown, der zum nächsten Event herunten zählt (ggf. Einstellung bei den Events, dass der Countdown auf dieses Event stattfinden soll?)
- Sobald Countdown abgelaufen: Nachricht, dass es gleich los geht: "Das Abenteuer beginnt in Kürze..." o.ä.
- Webseite soll optimal für Stream gestylt sein und mit Chatbox einbinden

**Comment by StevenPaw** [comment]
Added Countdown with 7c17568789a46c0bb766c26e5d081d47e0651be0
Only missing Chatbox now

**Comment by zwibblTV** [comment]
Chatbox added in OBS.
