### ISSUE TITLE
[BUG] Darkmode-Switch speichert nicht

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#16]
Wenn man in den nicht-darkmode geht und dann f5 drücket, dann wird es wieder dark.
 Überlegung: Cookie für 1 Monat, der die Einstellung speichert, sobald man sie ändert. Sonst Browser-Einstellung als Standard nutzen

**Comment by StevenPaw** [comment]
Fixed in b0876842e2988117b0252f58c22be0f9b4904c8a
