### ISSUE TITLE
[REQUEST] Teamunterseiten

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#18]
Unterseiten für jedes Teammitglied wie beim Halloweenhaus einfügen:

- Per klick auf den Nordländer gelangt man auf dessen Unterseite
- Auf der Unterseite gibt es einen Text, Bilder etc. über die Person

**Comment by StevenPaw** [comment]
Introduced with 11317e6fe3749a0759a817f30db1ab2fd08d9a92 with new Team-mechanic
