### ISSUE TITLE
[BUG] Sprachen und Social Media-Links oben rechts unsichtbar anklickbar

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#2]
Wenn man (bspw. auf der Startseite) runter scrollt, verschwinden bekanntlich rechts oben die Icons zum Ändern der Sprache und die Verlinkungen zu Social-Media. Anklickbar sind sie aber trotzdem...

**Comment by StevenPaw** [comment]
Fixed in 430d87b79737bea09436627f2a300ebc1e5a4cb7
