### ISSUE TITLE
[BUG] Abstand bei Aufzählungen verändern

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#20]
Aufzählungen werden noch nicht mit dem selben Abstand zwischen den Zeilen angezeigt, wie normaler Text. Vgl. dafür das Bild: Unten ist der Abstand zu klein
![image](https://user-images.githubusercontent.com/29929054/180416844-d7a5f479-48f9-45a3-a5f0-19b3db04007b.png)

**Comment by zwibblTV** [comment]
Aufzählungen sind auch noch in der falschen Farbe

**Comment by StevenPaw** [comment]
Fixed with 07b7951047fac102722dfc61c436e0c6e2908c5c
