### ISSUE TITLE
[REQUEST] RSS-Feed von News

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#21]
Ist es möglich, den RSS-Feed von den News zu abonnieren?

**Comment by StevenPaw** [comment]
First version in b0876842e2988117b0252f58c22be0f9b4904c8a
Needs further testing

**Comment by StevenPaw** [comment]
RSS-Feed-Titel muss noch angepasst werden. Ansonsten seit b0876842e2988117b0252f58c22be0f9b4904c8a hinzugefügt

**Comment by StevenPaw** [comment]
Finally added with ef0d48248630f92ad1d52999f2735a138e840ffa
