### ISSUE TITLE
[REQUEST] calculate age funktion

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#23]
Bitte eine Funktion oder einen [Shortcode](https://docs.silverstripe.org/en/4/developer_guides/extending/shortcodes/) hinzufügen, mit dem man sein Alter ausrechnen lassen kann

**Comment by StevenPaw** [comment]
Added with 8031709ecf3ec00d434cd8f58ad20e95066f6f25
