### ISSUE TITLE
[BUG] Event-Text links ausrichten

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#24]
Der Text von Events ist nicht gleich linksbündig, wenn kein Link vorhanden ist. Das muss angepasst werden.
![image](https://user-images.githubusercontent.com/29929054/180770052-70cea334-41ca-4f28-aade-b6f3c8b7fc7f.png)

**Comment by StevenPaw** [comment]
Fixed in b0876842e2988117b0252f58c22be0f9b4904c8a
