### ISSUE TITLE
[BUG] Team-URL too long

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#25]
Die URL der einzelnen Teammitglieder ist zu lang:
https://new.nordland-park.de/infos/team-uebersicht/view/Bennet_Martins/?source=/infos/ueber-uns/#e72
Nach dem Namen kann eigentlich Schluss sein

**Comment by StevenPaw** [comment]
Geht aus technischen grpünden nicht gerade besser. Da man von der Unterseite zurückkommen muss über den Zurück-button oben und aber ein Team-Element auf verschiedensten Seiten liegen kann ist die Quelle des Elements hinterlegt (?source=...)
Wenn du aber eine Unterseite alleine teilen willst, kannst du das einfach weglassen
