### ISSUE TITLE
[BUG] Darkmode: Change Linkcolor

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#26]
Im Darkmode ist die Farbe von Links unglücklicherweise blau auf blau. Gerne zu grau oder einer ähnlich weißen Farbe wechseln, damit die Optik dem non-dark-mode relativ ähnelt.
![image](https://user-images.githubusercontent.com/29929054/180864050-30c3043a-edab-4e87-9648-a2dd00e7eb6d.png)

**Comment by StevenPaw** [comment]
Fixed with 155839033e4bbe6af87784f064af74f7af1ca5b4
