### ISSUE TITLE
[BUG] Soziale Links auf Teamseite nebeneinander anordnen

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#27]
Auf den Teamseiten der einzelnen Nordländer sollten die sozialen Links nebeneinander (aber immerhin weiterhin mittig) angezeigt werden.
Das gibt dann auch ein konsistentes Bild zu den Links aus dem Footer

**Comment by StevenPaw** [comment]
Fixed with 3d4be56989251770272a0aa6a19e0027ebaab329
