### ISSUE TITLE
[BUG] Team Bild auf eigener Seite zu groß

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#28]
Meiner Meinung nach ist das Teambild auf der eigenen Seite viel zu groß.
Entweder kleiner oder hellblauer Kasten, der genau so breit wie der Text ist, in welchem Links das Bild und rechts daneben der Name, der Bereich und der Seit wann zu sehen ist. Ggf. Bild per klick vergrößern lassen?

**Comment by StevenPaw** [comment]
Fixed with c551181364c3c8994a319c8916386c560ac682e6
