### ISSUE TITLE
[BUG] Replace Home-Logo in lightmode

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#38]
Das Logo oben links, wenn man nach ganz oben gescrollt hat/ auf der Startseite, ist in der hellen Version schwer zu erkennen. Hier bitte gegen das blaue Logo austauschen.

**Comment by zwibblTV** [comment]
Bitte in der weiß-orangenen Version

**Comment by StevenPaw** [comment]
Fixed with 9dbdf1c4d4b64553716ab7e33f3f72ea7f1e44fe
