### ISSUE TITLE
[BUG] Styling of longer Attraktion title in docs

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#44]
Titel einer Attraktion in den Docs bitte kleiner machen oder anders stylen, wenn der Titel zu lang ist:
![image](https://user-images.githubusercontent.com/29929054/187032224-236a9e52-04a3-4eea-9c06-12e11a95a74d.png)

**Comment by StevenPaw** [comment]
Fixed in d2dc051c9f8881517d0c75e2d5c52250f23e65b2
