### ISSUE TITLE
[REQUEST] Custom Links

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#48]
Ggf. custom Links erstellen oder zumindest eine automatische Umlaut-umschreib-Funktion?
Bei den Nordländern besteht der Link aktuell aus Nordl%aender.

**Comment by StevenPaw** [comment]
Please provide example link

**Comment by zwibblTV** [comment]
Example Link: https://nordland-park.de/docs/view/Nordl%aender

**Comment by zwibblTV** [comment]
Next link: https://nordland-park.de/docs/attraction/Centerbühne

**Comment by StevenPaw** [comment]
Added with 00923982db6c23680a53d6c90ee0bc351ed1aa5d
