### ISSUE TITLE
[BUG] Text-Bild-Block Save-Crash

### ISSUE THREAD

**Issue by zwibblTV** [Nordland-Systems/nlp-website#8]
**Describe the bug**
Wenn man ein Text-Bild-Block mit Bild speichert, dann gibt es folgenden Fehler:
![photo_5352594802593614423_y](https://user-images.githubusercontent.com/29929054/178349026-140ec1bb-0a82-49c6-a4b8-efe6068e7344.jpg)

**Comment by StevenPaw** [comment]
Fixed in 6fdebee7e34278c4f046f04bb2f7f176924d83cf
